# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
user_name: Uldis
user_surname: Baurovskis
title: Game Development
email: uldis.baurovskis@gmail.com
description: My blog about game development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: HansaGames
github_username:  hersir88
highlighter: pygments

# Build settings
markdown: kramdown
