# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Game development inn
description: Game development blog

name: Uldis Baurovskis
twitter_url: https://twitter.com/HansaGames
github_url: https://github.com/Hersir88

paginate: 5
gems: ['jekyll-paginate']
